const candidates = [
  {
    id: 1,
    name: "김동연",
    slug: "kim-dong-yeon",
    party: "더불어민주당",
    position: "경기도지사",
    image: "images/kimdongyeon.jpg",
    promises: [
      {
        title: "중소기업 세금 감면 확대",
        slug: "중소기업-세금-감면-확대",
        description: "",
        source: "",
      },
      {
        title: "청년 일자리 100만개 창출",
        slug: "청년-일자리-100만개-창출",
        description: "",
        source: "",
      },
      {
        title: "디지털 경제 전환 지원금 도입",
        slug: "디지털-경제-전환-지원금-도입",
        description: "",
        source: "",
      },
      {
        title: "대학 등록금 50% 감면",
        slug: "대학-등록금-50-감면",
        description: "",
        source: "",
      },
      {
        title: "초중고 AI 교육 의무화",
        slug: "초중고-ai-교육-의무화",
        description: "",
        source: "",
      },
      {
        title: "농어촌 지역 교육 인프라 확충",
        slug: "농어촌-지역-교육-인프라-확충",
        description: "",
        source: "",
      },
      {
        title: "기초연금 인상",
        slug: "기초연금-인상",
        description: "",
        source: "",
      },
      {
        title: "영유아 무상 의료 서비스 확대",
        slug: "영유아-무상-의료-서비스-확대",
        description: "",
        source: "",
      },
      {
        title: "장애인 일자리 확대 및 지원금 인상",
        slug: "장애인-일자리-확대-및-지원금-인상",
        description: "",
        source: "",
      },
    ],
  },
  {
    id: 2,
    name: "이재명",
    slug: "lee-jae-myung",
    party: "더불어민주당",
    position: "국회의원",
    image: "images/leejaeming.jpg",
    promises: [
      {
        title: "기본소득 제도 도입",
        slug: "기본소득-제도-도입",
        description: "",
        source: "",
      },
      {
        title: "지역화폐 확대",
        slug: "지역화폐-확대",
        description: "",
        source: "",
      },
      {
        title: "공정경제 생태계 조성",
        slug: "공정경제-생태계-조성",
        description: "",
        source: "",
      },
      {
        title: "공공주택 100만호 공급",
        slug: "공공주택-100만호-공급",
        description: "",
        source: "",
      },
      {
        title: "1인 가구 주거지원 확대",
        slug: "1인-가구-주거지원-확대",
        description: "",
        source: "",
      },
      {
        title: "부동산 투기 근절",
        slug: "부동산-투기-근절",
        description: "",
        source: "",
      },
      {
        title: "전국민 고용보험 도입",
        slug: "전국민-고용보험-도입",
        description: "",
        source: "",
      },
      {
        title: "의료 공공성 강화",
        slug: "의료-공공성-강화",
        description: "",
        source: "",
      },
      {
        title: "돌봄 국가책임제 도입",
        slug: "돌봄-국가책임제-도입",
        description: "",
        source: "",
      },
    ],
  },
  {
    id: 3,
    name: "김경수",
    slug: "kim-kyung-soo",
    party: "더불어민주당",
    position: "전 경남도지사",
    image: "images/kimkyungsu.jpg",
    promises: [
      {
        title: "디지털 혁신 일자리 창출",
        slug: "디지털-혁신-일자리-창출",
        description: "",
        source: "",
      },
      {
        title: "스마트 산업단지 조성",
        slug: "스마트-산업단지-조성",
        description: "",
        source: "",
      },
      {
        title: "미래산업 육성",
        slug: "미래산업-육성",
        description: "",
        source: "",
      },
      {
        title: "지역 맞춤형 복지정책 확대",
        slug: "지역-맞춤형-복지정책-확대",
        description: "",
        source: "",
      },
      {
        title: "고령화 사회 대응 시스템 구축",
        slug: "고령화-사회-대응-시스템-구축",
        description: "",
        source: "",
      },
      {
        title: "돌봄 서비스 강화",
        slug: "돌봄-서비스-강화",
        description: "",
        source: "",
      },
      {
        title: "지역 교육격차 해소",
        slug: "지역-교육격차-해소",
        description: "",
        source: "",
      },
      {
        title: "평생학습 체계 구축",
        slug: "평생학습-체계-구축",
        description: "",
        source: "",
      },
      {
        title: "청년 취업 지원 프로그램 확대",
        slug: "청년-취업-지원-프로그램-확대",
        description: "",
        source: "",
      },
    ],
  },
  {
    id: 4,
    name: "이준석",
    slug: "lee-jun-seok",
    party: "개혁신당",
    position: "국회의원",
    image: "images/leejunseok.jpg",
    promises: [
      {
        title: "청년 주거지원 확대",
        slug: "청년-주거지원-확대",
        description: "",
        source: "",
      },
      {
        title: "청년 창업 지원 강화",
        slug: "청년-창업-지원-강화",
        description: "",
        source: "",
      },
      {
        title: "디지털 인재 양성",
        slug: "디지털-인재-양성",
        description: "",
        source: "",
      },
      {
        title: "교육 자율성 확대",
        slug: "교육-자율성-확대",
        description: "",
        source: "",
      },
      {
        title: "대학 서열화 해소",
        slug: "대학-서열화-해소",
        description: "",
        source: "",
      },
      {
        title: "직업교육 강화",
        slug: "직업교육-강화",
        description: "",
        source: "",
      },
      {
        title: "정치개혁 로드맵 실행",
        slug: "정치개혁-로드맵-실행",
        description: "",
        source: "",
      },
      {
        title: "디지털 정부 구현",
        slug: "디지털-정부-구현",
        description: "",
        source: "",
      },
      {
        title: "정치 세대교체 촉진",
        slug: "정치-세대교체-촉진",
        description: "",
        source: "",
      },
    ],
  },
  {
    id: 5,
    name: "안철수",
    slug: "ahn-cheol-soo",
    party: "국민의힘",
    position: "국회의원",
    image: "images/anchulsu.jpg",
    promises: [
      {
        title: "AI 기반 신산업 육성",
        slug: "ai-기반-신산업-육성",
        description: "",
        source: "",
      },
      {
        title: "바이오헬스 산업 지원 확대",
        slug: "바이오헬스-산업-지원-확대",
        description: "",
        source: "",
      },
      {
        title: "디지털 전환 가속화",
        slug: "디지털-전환-가속화",
        description: "",
        source: "",
      },
      {
        title: "벤처 창업 생태계 강화",
        slug: "벤처-창업-생태계-강화",
        description: "",
        source: "",
      },
      {
        title: "규제 샌드박스 확대",
        slug: "규제-샌드박스-확대",
        description: "",
        source: "",
      },
      {
        title: "중소기업 혁신 지원",
        slug: "중소기업-혁신-지원",
        description: "",
        source: "",
      },
      {
        title: "교육 플랫폼 혁신",
        slug: "교육-플랫폼-혁신",
        description: "",
        source: "",
      },
      {
        title: "STEM 교육 강화",
        slug: "stem-교육-강화",
        description: "",
        source: "",
      },
      {
        title: "평생교육 시스템 구축",
        slug: "평생교육-시스템-구축",
        description: "",
        source: "",
      },
    ],
  },
  {
    id: 6,
    name: "김문수",
    slug: "kim-moon-soo",
    party: "국민의힘",
    position: "전 고용노동부 장관",
    image: "images/kimmunsu.jpg",
    promises: [
      {
        title: "노동시장 유연안정성 강화",
        slug: "노동시장-유연안정성-강화",
        description: "",
        source: "",
      },
      {
        title: "중소기업 고용 지원 확대",
        slug: "중소기업-고용-지원-확대",
        description: "",
        source: "",
      },
      {
        title: "청년 일자리 미스매치 해소",
        slug: "청년-일자리-미스매치-해소",
        description: "",
        source: "",
      },
      {
        title: "기업 친화적 환경 조성",
        slug: "기업-친화적-환경-조성",
        description: "",
        source: "",
      },
      {
        title: "규제 혁파 및 경제 활성화",
        slug: "규제-혁파-및-경제-활성화",
        description: "",
        source: "",
      },
      {
        title: "세금 부담 완화",
        slug: "세금-부담-완화",
        description: "",
        source: "",
      },
      {
        title: "북한 인권 개선 압박",
        slug: "북한-인권-개선-압박",
        description: "",
        source: "",
      },
      {
        title: "강력한 안보 태세 구축",
        slug: "강력한-안보-태세-구축",
        description: "",
        source: "",
      },
      {
        title: "실용적 대북 정책 추진",
        slug: "실용적-대북-정책-추진",
        description: "",
        source: "",
      },
    ],
  },
  {
    id: 7,
    name: "한동훈",
    slug: "han-dong-hoon",
    party: "국민의힘",
    position: "전 법무장관",
    image: "images/handonghun.jpg",
    promises: [
      {
        title: "사법제도 개혁",
        slug: "사법제도-개혁",
        description: "",
        source: "",
      },
      {
        title: "검찰 독립성 강화",
        slug: "검찰-독립성-강화",
        description: "",
        source: "",
      },
      {
        title: "부패 척결 시스템 구축",
        slug: "부패-척결-시스템-구축",
        description: "",
        source: "",
      },
      {
        title: "범죄 예방 시스템 강화",
        slug: "범죄-예방-시스템-강화",
        description: "",
        source: "",
      },
      {
        title: "사이버 범죄 대응 역량 강화",
        slug: "사이버-범죄-대응-역량-강화",
        description: "",
        source: "",
      },
      {
        title: "아동·여성 보호 강화",
        slug: "아동여성-보호-강화",
        description: "",
        source: "",
      },
      {
        title: "법무행정 디지털화",
        slug: "법무행정-디지털화",
        description: "",
        source: "",
      },
      {
        title: "출입국 관리 시스템 개선",
        slug: "출입국-관리-시스템-개선",
        description: "",
        source: "",
      },
      {
        title: "교정시설 현대화",
        slug: "교정시설-현대화",
        description: "",
        source: "",
      },
    ],
  },
  {
    id: 8,
    name: "나경원",
    slug: "na-kyung-won",
    party: "국민의힘",
    position: "국회의원",
    image: "images/nakyungwon.jpg",
    promises: [
      {
        title: "육아휴직 급여 인상",
        slug: "육아휴직-급여-인상",
        description: "",
        source: "",
      },
      {
        title: "돌봄 인프라 확충",
        slug: "돌봄-인프라-확충",
        description: "",
        source: "",
      },
      {
        title: "경력단절 여성 지원 강화",
        slug: "경력단절-여성-지원-강화",
        description: "",
        source: "",
      },
      {
        title: "공교육 경쟁력 강화",
        slug: "공교육-경쟁력-강화",
        description: "",
        source: "",
      },
      {
        title: "사교육비